name: Release
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ğŸ”– Collect tag name
        id: tag
        run: |
          echo ::set-output name=TAG_NAME::${GITHUB_REF#refs/tags/}
      - name: ğŸ Build python package
        run: make python-build
      - name: ğŸ“¦ Upload python package to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/matcher-${{ steps.tag.outputs.TAG_NAME }}.tar.gz
          tag: ${{ github.ref }}
      - name : ğŸ‹ Build docker image
        run: make docker-build VERSION=${{ steps.tag.outputs.TAG_NAME }}
      - name: Login docker
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      - name: ğŸ“¦ Push docker image
        run: make docker-push VERSION=${{ steps.tag.outputs.TAG_NAME }}